# Generated by Django 3.2 on 2021-11-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userid',
            new_name='user',
        ),
    ]
